version: '3'

services:
  varnish:
    image: ealen/echo-server
    deploy:
      mode: replicated
      replicas: 4
  purger:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      PURGER_MODE: "compose"
      PURGER_SERVICE_NAME: varnish
      PURGER_SERVICE_PORT: 80
      PURGER_PUBLIC_SITES: "['site.example.com', 'cms.example.com']"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://localhost:4317
      OTEL_DEBUG: True
