name: Test Codebase

on:
  push:
  workflow_dispatch:

env:
  PACKAGE_PATH: cluster_purger
  IMAGE_NAME: ghcr.io/kitconcept/cluster-purger
  PYTHON_VERSION: 3.11

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'

      - name: "Install Packages"
        run: poetry install

      - name: "Black"
        run: poetry run black --check --diff ${{ env.PACKAGE_PATH }}

      - name: "iSort"
        run: poetry run isort --check-only ${{ env.PACKAGE_PATH }}

      - name: "Flake 8"
        run: poetry run flakeheaven lint ${{ env.PACKAGE_PATH }}

      - name: "Test Codebase"
        run: poetry run pytest

  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - test

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=raw,value=latest,enable={{ is_default_branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
